## TENSORS
这部分用于学习`Tensor`的有关内容，

In [33]:
import torch
import numpy as np

### Tensor的初始化
`Tensors`有多种方式可以初始化，这里主要介绍这四种

* Directly from data

* From a NumPy array

* From another tensor:

* With random or constant values:



In [34]:
# 1.直接用列表创建
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"x_data:\n{x_data}\n")

#2.用Numpy创建
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"x_np:\n{x_np}\n")

# 3.用其它Tensor创建
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

# 4.用随机数或常值
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")


x_data:
tensor([[1, 2],
        [3, 4]])

x_np:
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.0940, 0.0503],
        [0.6445, 0.8530]]) 

Random Tensor: 
 tensor([[0.1245, 0.4561, 0.5229],
        [0.0460, 0.6338, 0.8059]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### `Tensor`的属性
`Tensor`有以下三个属性

* `tensor.shape`
* `tensor.dtype`
* `tensor.device`

In [35]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### `Tensor`的运算
事实上，`tensor`的运算超过$100$多种$^{[1]}$,包括转置、索引、切片、数学运算、线性代数、随机采样等

此处我们演示常见的一些操作，包括

* 索引和切片
* `torch.cat`连接张量$^{[2]}$
* 张量相乘
* 就地操作$^{[3]}$

> $[1]$ https://pytorch.org/docs/stable/torch.html 这里包括了`pytorch`中`tensor`的全部运算
> 
> $[2]$ https://pytorch.org/docs/stable/generated/torch.stack.html 可以在`torch.stack`查看更多有关操作
> 
> $[3]$ 就地操作可以节省一些内存，但在计算导数时可能会出现问题，因为历史记录会立即丢失。因此，不鼓励使用它们。




在这里，我们可以使`tensor`运算在我们的`GPU`上，代码如下所示：

In [36]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

# 或者可以直接判断是否有着可用的GPU
print(torch.cuda.is_available())

False


下面来演示几个运算操作:

In [37]:
tensor = torch.ones(4, 4)
tensor[:2,1:3] = 0
print(tensor)

tensor([[1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [38]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
print(t1.shape)

tensor([[1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1.],
        [1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
torch.Size([4, 12])


In [39]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")
# 这里是对应元素相乘 也就是 Hadamard product

tensor.mul(tensor) 
 tensor([[1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [40]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 4., 4.],
        [2., 2., 4., 4.]]) 

tensor @ tensor.T 
 tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 4., 4.],
        [2., 2., 4., 4.]])


In [41]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 0., 1.],
        [1., 0., 0., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

tensor([[6., 5., 5., 6.],
        [6., 5., 5., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


### `numpy`与`tensor`
CPU 和 NumPy 数组上的张量可以共享其底层内存位置，改变其中一个就会改变另一个。



In [44]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


反过来也是成立的

In [45]:
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
